name: ci
on: [push]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          # All of the Git history is required for day8/lein-git-inject to determine the version string.
          fetch-depth: 0

      - name: Setup java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@e6e77cdf6873b7af18609cf29f24bee054c5be72 # 13.5
        with:
          lein: 'latest'

      - name: Maven cache
        id: maven-cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('project.clj') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run lein test
        if: steps.maven-cache.outputs.cache-hit != 'true'
        run: lein test

      - name: Run lein -o test
        if: steps.maven-cache.outputs.cache-hit == 'true'
        run: lein -o test

      - name: Slack notification
        if: failure() || cancelled()
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v3
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          # yamllint disable-line rule:line-length
          payload: '{"channel":"#oss-robots","text":"shadow-git-inject Tests ${{ job.status }}\n<${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|`${{ github.sha }}`> · <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"}'
